export const ROUTES = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    me: "/auth/me",
    logout: "/auth/logout",
  },
    products: {
    getAll: "/products",            
    getById: (id: string) => `/products/${id}`,  
    create: "/products",           
    update: (id: string) => `/products/${id}`, 
    delete: (id: string) => `/products/${id}`,  
    bulkDelete: "/products/bulk-delete", 
  },
  categories: {
  getAll: "/categories",
  getById: (id: string) => `/categories/${id}`,
  create: "/categories",
  update: (id: string) => `/categories/${id}`,
  delete: (id: string) => `/categories/${id}`,
  bulkDelete: "/categories/bulk-delete",
},
 brands: {
    getAll: "/brands",
    getById: (id: string) => `/brands/${id}`,
    create: "/brands",
    update: (id: string) => `/brands/${id}`,
    delete: (id: string) => `/brands/${id}`,
    bulkDelete: "/brands/bulk-delete",
  },
  types: {
  getAll: "/types",
  getById: (id: string) => `/types/${id}`,
  create: "/types",
  update: (id: string) => `/types/${id}`,
  delete: (id: string) => `/types/${id}`,
  bulkDelete: "/types/bulk-delete",
},
 fabrics: {
    getAll: "/fabrics",
    getById: (id: string) => `/fabrics/${id}`,
    create: "/fabrics",
    update: (id: string) => `/fabrics/${id}`,
    delete: (id: string) => `/fabrics/${id}`,
    bulkDelete: "/fabrics/bulk-delete",
  },
  productLabels: {
    getAll: "/product-labels",
    getById: (id: string) => `/product-labels/${id}`,
    create: "/product-labels",
    update: (id: string) => `/product-labels/${id}`,
    delete: (id: string) => `/product-labels/${id}`,
    bulkDelete: "/product-labels/bulk-delete",
  },
   colors: {
    getAll: "/colors",
    getById: (id: string) => `/colors/${id}`,
    create: "/colors",
    update: (id: string) => `/colors/${id}`,
    delete: (id: string) => `/colors/${id}`,
    bulkDelete: "/colors/bulk-delete",
  },
  sizes: {
    getAll: "/sizes",
    getById: (id: string) => `/sizes/${id}`,
    create: "/sizes",
    update: (id: string) => `/sizes/${id}`,
    delete: (id: string) => `/sizes/${id}`,
    bulkDelete: "/sizes/bulk-delete",
  },
upload:{
image:"/uploads/image"
},
discounts: {
    getAll: "/discounts",
    getById: (id: string) => `/discounts/${id}`,
    create: "/discounts",
    update: (id: string) => `/discounts/${id}`,
    delete: (id: string) => `/discounts/${id}`,
    bulkDelete: "/discounts/bulk-delete",
  },
   coupons: {
    getAll: "/coupons",
    getById: (id: string) => `/coupons/${id}`,
    create: "/coupons",
    update: (id: string) => `/coupons/${id}`,
    delete: (id: string) => `/coupons/${id}`,
    bulkDelete: "/coupons/bulk-delete",
  },
orders : {
  getAll: "/orders",
  getById: (id: string) => `/orders/${id}`,
  create: "/orders",
  update: (id: string) => `/orders/${id}`,
  delete: (id: string) => `/orders/${id}`,
  bulkDelete: "/orders/bulk-delete",
},
payments : {
  getAll: "/payments",
  getById: (id: string) => `/payments/${id}`,
  delete: (id: string) => `/payments/${id}`,
  bulkDelete: "/payments/bulk-delete",
},
 users : {
     getAll: "/users",
    getStoreCustomers: "/users/store/customers",
    getById: (id: string) => `/users/${id}`,
    create: "/users",
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    bulkDelete: "/users/bulk-delete",
},
 profile: {
    get: "/users/me",
    update: "/users/me", 
  },
  settings: {
  get: "/settings",
  update: "/settings",
},
customerReviews: {
  getAll: "/customer-reviews",
  getById: (id: string) => `/customer-reviews/${id}`,
  delete: (id: string) => `/customer-reviews/${id}`,
  bulkDelete: "/customer-reviews/bulk-delete",
},
cart : {
  getAll: "/carts",               
  getById: (id: string) => `/carts/${id}`, 
  delete: (id: string) => `/carts/${id}`, 
   bulkDelete: "/carts/bulk-delete",
},
wishlist: {
  getAll: "/wishlists",      
  getById: (id: string) => `/wishlists/${id}`, 
  delete: (id: string) => `/wishlists/${id}`, 
  bulkDelete: "/wishlists/bulk-delete",        
},
contactUs: {
  getAll: "/contact-us",              
  getById: (id: string) => `/contact-us/${id}`, 
  delete: (id: string) => `/contact-us/${id}`,  
  bulkDelete: "/contact-us/bulk-delete",        
},
sections: {
  getAll: "/sections",
  getById: (id: string) => `/sections/${id}`,
  create: "/sections",
  update: (id: string) => `/sections/${id}`,
  delete: (id: string) => `/sections/${id}`,
  bulkDelete: "/sections/bulk-delete",
},
navbar: {
  getAll: "/navbar",
  getById: (id: string) => `/navbar/${id}`,
  create: "/navbar",
  update: (id: string) => `/navbar/${id}`,
  delete: (id: string) => `/navbar/${id}`,
  bulkDelete: "/navbar/bulk-delete",
},
footer: {
  getAll: "/footer",
  getById: (id: string) => `/footer/${id}`,
  create: "/footer",
  update: (id: string) => `/footer/${id}`,
  delete: (id: string) => `/footer/${id}`,
  bulkDelete: "/footer/bulk-delete",
},
stores: {
    getAll: "/stores",
    getById: (id: string) => `/stores/${id}`,
    create: "/stores",
    update: (id: string) => `/stores/${id}`,
    delete: (id: string) => `/stores/${id}`,
    bulkDelete: "/stores/bulk-delete",
  },
};
