export const ROUTES = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    logout: "/auth/logout",
  },
    products: {
    getAll: "/products",            
    getById: (id: string) => `/products/${id}`,  
    create: "/products",           
    update: (id: string) => `/products/${id}`, 
    delete: (id: string) => `/products/${id}`,  
    bulkDelete: "/products/bulk-delete", 
  },
  categories: {
  getAll: "/categories",
  getById: (id: string) => `/categories/${id}`,
  create: "/categories",
  update: (id: string) => `/categories/${id}`,
  delete: (id: string) => `/categories/${id}`,
  bulkDelete: "/categories/bulk-delete",
},
 brands: {
    getAll: "/brands",
    getById: (id: string) => `/brands/${id}`,
    create: "/brands",
    update: (id: string) => `/brands/${id}`,
    delete: (id: string) => `/brands/${id}`,
    bulkDelete: "/brands/bulk-delete",
  },
  types: {
  getAll: "/types",
  getById: (id: string) => `/types/${id}`,
  create: "/types",
  update: (id: string) => `/types/${id}`,
  delete: (id: string) => `/types/${id}`,
  bulkDelete: "/types/bulk-delete",
},
 fabrics: {
    getAll: "/fabrics",
    getById: (id: string) => `/fabrics/${id}`,
    create: "/fabrics",
    update: (id: string) => `/fabrics/${id}`,
    delete: (id: string) => `/fabrics/${id}`,
    bulkDelete: "/fabrics/bulk-delete",
  },
  productLabels: {
    getAll: "/product-labels",
    getById: (id: string) => `/product-labels/${id}`,
    create: "/product-labels",
    update: (id: string) => `/product-labels/${id}`,
    delete: (id: string) => `/product-labels/${id}`,
    bulkDelete: "/product-labels/bulk-delete",
  },
   colors: {
    getAll: "/colors",
    getById: (id: string) => `/colors/${id}`,
    create: "/colors",
    update: (id: string) => `/colors/${id}`,
    delete: (id: string) => `/colors/${id}`,
    bulkDelete: "/colors/bulk-delete",
  },
  sizes: {
    getAll: "/sizes",
    getById: (id: string) => `/sizes/${id}`,
    create: "/sizes",
    update: (id: string) => `/sizes/${id}`,
    delete: (id: string) => `/sizes/${id}`,
    bulkDelete: "/sizes/bulk-delete",
  },
upload:{
image:"/uploads/image"
},
  users: {
    list: "/users",
    get: (id: string) => `/users/${id}`,
    create: "/users",
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    bulkDelete: "/users/bulk-delete",
  },
  pages: {
    list: "/pages",
    get: (id: string) => `/pages/${id}`,
    create: "/pages",
    update: (id: string) => `/pages/${id}`,
    delete: (id: string) => `/pages/${id}`,
    bulkDelete: "/pages/bulk-delete",
  },
  newsCategories: {
    list: "/news-categories",
    get: (id: string) => `/news-categories/${id}`,
    create: "/news-categories",
    update: (id: string) => `/news-categories/${id}`,
    delete: (id: string) => `/news-categories/${id}`,
    bulkDelete: "/news-categories/bulk-delete",
  },
  news: {
    list: "/news",
    get: (id: string) => `/news/${id}`,
    create: "/news",
    update: (id: string) => `/news/${id}`,
    delete: (id: string) => `/news/${id}`,
    bulkDelete: "/news/bulk-delete",
  },
  payments: {
    list: "/payments",
    stats: "/payments/stats",
  },
};
